/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import * as nestAccessControl from "nest-access-control";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateVerificationTokenArgs } from "./CreateVerificationTokenArgs";
import { UpdateVerificationTokenArgs } from "./UpdateVerificationTokenArgs";
import { DeleteVerificationTokenArgs } from "./DeleteVerificationTokenArgs";
import { VerificationTokenFindManyArgs } from "./VerificationTokenFindManyArgs";
import { VerificationTokenFindUniqueArgs } from "./VerificationTokenFindUniqueArgs";
import { VerificationToken } from "./VerificationToken";
import { VerificationTokenService } from "../verificationToken.service";

@graphql.Resolver(() => VerificationToken)
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
export class VerificationTokenResolverBase {
  constructor(
    protected readonly service: VerificationTokenService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "any",
  })
  async _verificationTokensMeta(
    @graphql.Args() args: VerificationTokenFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [VerificationToken])
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "any",
  })
  async verificationTokens(
    @graphql.Args() args: VerificationTokenFindManyArgs
  ): Promise<VerificationToken[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => VerificationToken, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "read",
    possession: "own",
  })
  async verificationToken(
    @graphql.Args() args: VerificationTokenFindUniqueArgs
  ): Promise<VerificationToken | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "create",
    possession: "any",
  })
  async createVerificationToken(
    @graphql.Args() args: CreateVerificationTokenArgs
  ): Promise<VerificationToken> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "update",
    possession: "any",
  })
  async updateVerificationToken(
    @graphql.Args() args: UpdateVerificationTokenArgs
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => VerificationToken)
  @nestAccessControl.UseRoles({
    resource: "VerificationToken",
    action: "delete",
    possession: "any",
  })
  async deleteVerificationToken(
    @graphql.Args() args: DeleteVerificationTokenArgs
  ): Promise<VerificationToken | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
